# Site settings
title: Alex Lockhart

# User settings
username: Alex Lockhart
user_subtitle: Software Developer
email: me@alexlockhart.ca
twitter_username: salexlockhart
github_username:  salockhart
linkedin_username:  salockhart

sass:
  sass_dir: css
  style: compressed
