# Site settings
title: Alex Lockhart
description: A blog about me.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Lockhart
user_subtitle: Software Developer
user_description: Full Stack Software Developer from Halifax, NS
email: salexlockhart@gmail.com
twitter_username: salexlockhart
github_username:  salockhart
linkedin_username:  salockhart

skills:
  - devicon-amazonwebservices-plain-wordmark
  - devicon-android-plain
  - devicon-apple-original
  - devicon-atom-original
  - devicon-css3-plain
  - devicon-docker-plain
  - devicon-firefox-plain
  - devicon-git-plain
  - devicon-heroku-original
  - devicon-html5-plain
  - devicon-javascript-plain
  - devicon-mongodb-plain-wordmark
  - devicon-nodejs-plain-wordmark
  - devicon-react-original
  - devicon-sass-original
  -

# Google-analytics
google-analytics:
  id: ""

sass:
  sass_dir: css
  style: compressed
