# Site settings
title: Alex Lockhart
description: A blog about me.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Lockhart
user_subtitle: Full Stack Software Developer
user_description: Halifax, NS
email: salexlockhart@gmail.com
twitter_username: salexlockhart
github_username:  salockhart
linkedin_username:  salockhart

# Google-analytics
google-analytics:
  id: ""

sass:
  sass_dir: css
  style: compressed
